/**
 * Config renderers.
 *
 * One generated profile can be emitted in several formats:
 *   - `.conf` for AmneziaWG / awg-quick (obfuscation parameters included)
 *   - `.conf` for stock WireGuard / wg-quick (obfuscation stripped)
 *   - JSON, for scripting and for re-importing into this tool
 */

import { renderObfuscationLines } from "./amnezia.js"

/** Escape nothing, but keep line endings consistent across OSes. */
function join(lines) {
	return lines.filter((l) => l !== null && l !== undefined).join("\n") + "\n"
}

/**
 * Build the shared header comment block.
 * @param {Object} profile
 * @param {string} flavor
 */
function header(profile, flavor) {
	const { meta, warp, obfuscation } = profile
	const lines = [
		`# ${flavor} configuration generated by AWG WARP Architect`,
		`# Generated: ${meta.generatedAt}`,
		`# Profile seed: ${meta.seed}   <- reuse this seed to reproduce identical obfuscation parameters`,
	]
	if (warp?.accountType) {
		lines.push(`# WARP account: ${warp.accountType}${warp.warpPlus ? " (WARP+)" : ""}`)
	}
	if (obfuscation?.enabled) {
		lines.push(`# Obfuscation: ${obfuscation.profileLabel} (AmneziaWG ${obfuscation.version})`)
	}
	if (obfuscation?.compat === "awg") {
		// The single most expensive mistake this tool can let you make: these
		// parameters import cleanly, show no error, and never complete a handshake
		// against Cloudflare, because WARP servers run stock WireGuard.
		lines.push("#")
		lines.push("# !!! THIS PROFILE WILL NOT CONNECT TO CLOUDFLARE WARP !!!")
		lines.push("# S1/S2 padding, H1-H4 magic headers and I1-I5 fake packets are")
		lines.push("# AmneziaWG extensions. Cloudflare speaks stock WireGuard and will")
		lines.push("# silently drop the handshake. Point this config at your own")
		lines.push("# AmneziaWG server, or pick a warp-* profile instead.")
	} else if (obfuscation?.enabled) {
		lines.push("# WARP-compatible: junk packets (Jc/Jmin/Jmax) only, which stock")
		lines.push("# WireGuard ignores, and no S1/S2 padding, so the handshake works.")
		if (obfuscation.headersFromClientId) {
			lines.push("# H1-H4 are present and deliberately not random: they carry the")
			lines.push("# Cloudflare client_id, exactly as the official WARP client does.")
		}
	}
	if (meta.mock) {
		lines.push("#")
		lines.push("# !!! MOCK MODE !!! These credentials are synthetic and will NOT connect.")
		lines.push("# Unset MOCK_WARP to register a real device with Cloudflare.")
	}
	lines.push("#")
	lines.push("# Keep PrivateKey secret. Anyone holding it can use this tunnel as you.")
	return lines
}

/**
 * Render an AmneziaWG config (awg-quick / AmneziaVPN / AmneziaWG apps).
 * @param {Object} profile
 * @returns {string}
 */
export function renderAmneziaWG(profile) {
	const { keys, warp, network, endpoint, obfuscation } = profile

	const lines = [
		...header(profile, "AmneziaWG"),
		"",
		"[Interface]",
		`PrivateKey = ${keys.privateKey}`,
		`Address = ${network.addresses.join(", ")}`,
		`DNS = ${network.dns.join(", ")}`,
		`MTU = ${network.mtu}`,
	]

	const obfLines = renderObfuscationLines(obfuscation)
	if (obfLines.length) {
		lines.push("")
		lines.push("# --- AmneziaWG obfuscation ---")
		lines.push("# Every peer MUST use these exact values or the handshake fails.")
		lines.push(...obfLines)
	}

	lines.push("")
	lines.push("[Peer]")
	lines.push(`PublicKey = ${warp.peerPublicKey}`)
	if (network.presharedKey) lines.push(`PresharedKey = ${network.presharedKey}`)
	lines.push(`AllowedIPs = ${network.allowedIps.join(", ")}`)
	lines.push(`Endpoint = ${endpoint.endpoint}`)
	if (network.keepalive) lines.push(`PersistentKeepalive = ${network.keepalive}`)

	if (warp.reserved) {
		lines.push("")
		lines.push(`# Cloudflare client_id = ${warp.reserved.base64}`)
		lines.push(`# Reserved bytes = [${warp.reserved.bytes.join(", ")}]`)
		if (obfuscation?.headersFromClientId) {
			lines.push("# These bytes are folded into H1-H4 above, which is exactly how the")
			lines.push("# official WARP client marks its packets. The low byte still carries")
			lines.push("# the real message type, so Cloudflare accepts the packet, and the")
			lines.push("# header stops being a constant 01/02/03/04 for anyone watching.")
		} else {
			lines.push("# WARNING: this config does NOT carry them in the header. Cloudflare")
			lines.push("# completes the handshake and can still drop every transport packet,")
			lines.push("# which looks exactly like 'connected, but no internet'. Regenerate")
			lines.push("# without --no-client-id-headers, or use a client that sets Reserved.")
		}
	}

	return join(lines)
}

/**
 * Render a plain WireGuard config. Obfuscation is stripped, because wg-quick
 * errors out on unknown keys rather than ignoring them.
 * @param {Object} profile
 * @returns {string}
 */
export function renderWireGuard(profile) {
	const { keys, warp, network, endpoint } = profile

	const lines = [
		...header(profile, "WireGuard"),
		"# Obfuscation parameters are intentionally omitted: stock wg-quick rejects them.",
		"#",
		"# Two consequences, both of them yours to live with: stock WireGuard cannot",
		"# write the Cloudflare client_id into the reserved header bytes, and it sends",
		"# a textbook handshake that DPI recognises instantly. Prefer the AmneziaWG",
		"# file; keep this one only for clients that cannot read the other format.",
		"",
		"[Interface]",
		`PrivateKey = ${keys.privateKey}`,
		`Address = ${network.addresses.join(", ")}`,
		`DNS = ${network.dns.join(", ")}`,
		`MTU = ${network.mtu}`,
		"",
		"[Peer]",
		`PublicKey = ${warp.peerPublicKey}`,
	]
	if (network.presharedKey) lines.push(`PresharedKey = ${network.presharedKey}`)
	lines.push(`AllowedIPs = ${network.allowedIps.join(", ")}`)
	lines.push(`Endpoint = ${endpoint.endpoint}`)
	if (network.keepalive) lines.push(`PersistentKeepalive = ${network.keepalive}`)

	return join(lines)
}

/**
 * Machine-readable form of the profile. Secrets are included, since this is
 * what the user downloads; the server never persists it.
 * @param {Object} profile
 */
export function renderJson(profile) {
	return JSON.stringify(
		{
			meta: profile.meta,
			interface: {
				privateKey: profile.keys.privateKey,
				publicKey: profile.keys.publicKey,
				addresses: profile.network.addresses,
				dns: profile.network.dns,
				mtu: profile.network.mtu,
			},
			peer: {
				publicKey: profile.warp.peerPublicKey,
				endpoint: profile.endpoint.endpoint,
				allowedIps: profile.network.allowedIps,
				persistentKeepalive: profile.network.keepalive,
				reserved: profile.warp.reserved?.bytes ?? null,
			},
			obfuscation: profile.obfuscation.enabled
				? {
						profile: profile.obfuscation.profile,
						version: profile.obfuscation.version,
						seed: profile.obfuscation.seed,
						...profile.obfuscation.params,
						signatures: profile.obfuscation.signatures.map((s) => ({
							key: s.key,
							id: s.id,
							template: s.template,
						})),
					}
				: { enabled: false },
			account: {
				type: profile.warp.accountType,
				warpPlus: profile.warp.warpPlus,
				registrationId: profile.warp.registrationId,
			},
		},
		null,
		2,
	)
}

/**
 * Suggested download filename. Interface names are limited to 15 characters on
 * Linux, and awg-quick derives the interface name from the filename, so keep
 * the stem short.
 * @param {Object} profile
 * @param {"awg"|"wg"|"json"} kind
 */
export function suggestFilename(profile, kind) {
	const tag = profile.meta.seed.slice(0, 6)
	if (kind === "json") return `warp-${tag}.json`
	if (kind === "wg") return `wg-${tag}.conf`
	return `awg-${tag}.conf`
}

/**
 * Render every format at once.
 * @param {Object} profile
 */
export function renderAll(profile) {
	return {
		amneziawg: {
			filename: suggestFilename(profile, "awg"),
			content: renderAmneziaWG(profile),
		},
		wireguard: {
			filename: suggestFilename(profile, "wg"),
			content: renderWireGuard(profile),
		},
		json: {
			filename: suggestFilename(profile, "json"),
			content: renderJson(profile),
		},
	}
}
